services:
  dysyncengine:
    build: .
    image: ghcr.io/plsy1/dy_sync_engine:latest
    container_name: dysyncengine
    ports:
      - "80:80"
    volumes:
      # Persistent database folder
      - ./data:/app/backend/data
      # Downloaded videos/assets
      - ./videos:/app/videos
      # Custom config for external API
      - ./config/douyin_web/config.yaml:/app/3rd/douyin_api/crawlers/douyin/web/config.yaml
      - ./config/tiktok_web/config.yaml:/app/3rd/douyin_api/crawlers/tiktok/web/config.yaml
      - ./config/tiktok_app/config.yaml:/app/3rd/douyin_api/crawlers/tiktok/app/config.yaml
      # Custom config (optional, can also use env vars)
    environment:
      - PORT=80
      - PYTHONUNBUFFERED=1
      # Example ENV overrides for config.yaml
      - SAVE_DIR=videos
    restart: unless-stopped
